
class WS_EVENT:
    SEND_PERSONAL_MESSAGE = "SEND_PERSONAL_MESSAGE"
    SEND_GROUP_MESSAGE = "SEND_GROUP_MESSAGE"
    RECEIVE_PERSONAL_MESSAGE = "RECEIVE_PERSONAL_MESSAGE"
    RECEIVE_GROUP_MESSAGE = "RECEIVE_GROUP_MESSAGE"
    PERSONAL_MESSAGE_DELIVERED = "PERSONAL_MESSAGE_DELIVERED"
    GROUP_CREATED = "GROUP_CREATED"
    ERROR = "ERROR"

ws_event = WS_EVENT()
